GET https://finance.naver.com/item/sise_time.naver?code=205470&thistime=20241119161049&page=2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
